// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


// import Navbar from "./components/Navbar";
// import "./globals.css";

// export const metadata = {
//   title: "News Bullet Kerala",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         {/* <Navbar /> */}
//         {children}
//       </body>
//     </html>
//   );
// }

import { Toaster } from "react-hot-toast";
import "./globals.css";
import Script from "next/script";

export const metadata = {
  title: "News Bullet Kerala",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://checkout.razorpay.com/v1/checkout.js"
          strategy="afterInteractive"
        />
      </head>

      <body>
           <Toaster position="top-right" reverseOrder={false} />
        {children}
      </body>
    </html>
  );
}
